language: haskell
cache:
  directories:
  - $HOME/.cabal
sudo: false
install:
  - cabal install idris
script:
  - idris --check cube.idr  
notifications:
  email: false
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
